### ISSUE TITLE
Wildcard definition bug

### ISSUE THREAD

**Issue by kocsismate** [PHP-DI/PHP-DI#282]
Hey,

I want to use wildcard definitions in PHP DI 5.0.0 the following way:

```php
$definitions = [
   'Src\*\Domain\*RepositoryInterface' => DI\object('Src\*\Infrastructure\Eloquent*Repository')
];
```

but it gives a fatal error:

```php
Fatal error: Uncaught exception 'RuntimeException' with message 'No definition resolver was configured for definition of type DI\Definition\ClassDefinition' in /website/vendor/php-di/php-> di/src/DI/Definition/Resolver/ResolverDispatcher.php:138
Stack trace: #0 /website/vendor/php-di/php-di/src/DI/Definition/Resolver/ResolverDispatcher.php(73): DI\Definition\Resolver\ResolverDispatcher->getDefinitionResolver(Object(DI\Definition\ClassDefinition))
#1 /website/vendor/php-di/php-di/src/DI/Container.php(206): DI\Definition\Resolver\ResolverDispatcher->isResolvable(Object(DI\Definition\ClassDefinition))
#2 /website/vendor/php-di/php-di/src/DI/Definition/Resolver/AliasResolver.php(65): DI\Container->has('Src\\Social\\User...')
#3 /website/vendor/php-di/php-di/src/DI/Definition/Resolver/ResolverDispatcher.php(75): DI\Definition\Resolver\AliasResolver->isResolvable(Object(DI\Definition\AliasDefinition), Array)
#4 /website/vendor/php-di/php-di/src/DI/Definition/Resolver/ParameterResolver.php(82): DI\Definition\Resolver\ResolverDispa in /website/vendor/php-di/php-di/src/DI/Definition/Resolver/ResolverDispatcher.php on line 138
```

However it used to work in beta 1 (but not in RC1)!

**Comment by kocsismate** [comment]
It turned out that Couscous 1.1 mixed things up! it requires "mnapoli/php-di-5" and I believe it caused the error. When I removed Couscous everything worked fine. So please, release a new version for Couscous!

**Comment by mnapoli** [comment]
Ah good catch, got bitten by this too :/ I now install Couscous with the phar. By the way the latest releases should fix that: https://github.com/CouscousPHP/Couscous/releases
