### ISSUE TITLE
PhpFileCache doesn't seem to work

### ISSUE THREAD

**Issue by dantleech** [PHP-DI/PHP-DI#402]
When using Doctrine PhpFileCache I get:

```bash
PHP Fatal error:  Uncaught InvalidArgumentException: Invalid argument given, PhpFileCache only allows objects that implement __set_state() and fully support var_export(). You can
 use the FilesystemCache to save arbitrary object graphs using serialize()/deserialize(). in /home/daniel/www/phpbench/container-benchmarks/vendor/doctrine/cache/lib/Doctrine/Common/Cache/PhpFileCache.php:82
    Stack trace:
    #0 /home/daniel/www/phpbench/container-benchmarks/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(132): Doctrine\Common\Cache\PhpFileCache->doSave('[DI\\Definition\\...', Object(DI\Definition\ObjectDefinition), 0)
    #1 /home/daniel/www/phpbench/container-benchmarks/vendor/php-di/php-di/src/DI/Definition/Source/CachedDefinitionSource.php(95): Doctrine\Common\Cache\CacheProvider->save('DI\\Definition\\b...', Object(DI\Definition\ObjectDefinition))
    #2 /home/daniel/www/phpbench/container-benchmarks/vendor/php-di/php-di/src/DI/Definition/Source/CachedDefinitionSource.php(51): DI\Definition\Source\CachedDefinitionSource->save in /home/daniel/www/phpbench/container-benchmarks/vendor/
doctrine/cache/lib/Doctrine/Common/Cache/PhpFileCache.php on line 82
```

I note that its listed in the [documentation](http://php-di.org/doc/performances.html).

**Comment by mnapoli** [comment]
Thanks! I've updated the documentation to reflect this, I guess you can use FilesystemCache instead so it's not a blocker issue right?

**Comment by dantleech** [comment]
Yes, FilesystemCache works fine, thanks for the quick response :)
