### ISSUE TITLE
ToDo: investigate "Access to undeclared static property"

### ISSUE THREAD

**Issue by holtkamp** [PHP-DI/PHP-DI#457]
Still have to investigate further, but since a few weeks incidentally the following error pops up in logs:

```
Access to undeclared static property: ProxyManagerGeneratedProxy\__PM__\Application\Domain\Repository\Entity\Category\ProductTypeRepository\Generated8f3a50c4b4ae195b0bf3659edd323b43::$publicProperties58c3c45355cf4243190962#0 /app/data/dependencyInjectionContainerProxies/ProxyManagerGeneratedProxy__PM__ApplicationDomainRepositoryEntityCategoryProductTypeRepositoryGenerated8f3a50c4b4ae195b0bf3659edd323b43.php(528): ProxyManagerGeneratedProxy\__PM__\Application\Domain\Repository\Entity\Category\ProductTypeRepository\Generated8f3a50c4b4ae195b0bf3659edd323b43->__get('initializer58c3...')
#1 /app/data/dependencyInjectionContainerProxies/ProxyManagerGeneratedProxy__PM__ApplicationDomainRepositoryEntityCategoryProductTypeRepositoryGenerated8f3a50c4b4ae195b0bf3659edd323b43.php(449): ProxyManagerGeneratedProxy\__PM__\Application\Domain\Repository\Entity\Category\ProductTypeRepository\Generated8f3a50c4b4ae195b0bf3659edd323b43->__set('initializer58c3...', Object(Closure))
#2 /app/vendor/ocramius/proxy-manager/src/ProxyManager/Factory/LazyLoadingValueHolderFactory.php(47): ProxyManagerGeneratedProxy\__PM__\Application\Domain\Repository\Entity\Category\ProductTypeRepository\Generated8f3a50c4b4ae195b0bf3659edd323b43::staticProxyConstructor(Object(Closure))
#3 /app/vendor/php-di/php-di/src/DI/Proxy/ProxyFactory.php(59): ProxyManager\Factory\LazyLoadingValueHolderFactory->createProxy('Application\\Domain\\Rep...', Object(Closure))
#4 /app/vendor/php-di/php-di/src/DI/Definition/Resolver/ObjectCreator.php(103): DI\Proxy\ProxyFactory->createProxy('Application\\Domain\\Rep...', Object(Closure))
#5 /app/vendor/php-di/php-di/src/DI/Definition/Resolver/ObjectCreator.php(67): DI\Definition\Resolver\ObjectCreator->createProxy(Object(DI\Definition\ObjectDefinition), Array)
#6 /app/vendor/php-di/php-di/src/DI/Definition/Resolver/ResolverDispatcher.php(58): DI\Definition\Resolver\ObjectCreator->resolve(Object(DI\Definition\ObjectDefinition), Array)
#7 /app/vendor/php-di/php-di/src/DI/Container.php(285): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\ObjectDefinition), Array)
#8 /app/vendor/php-di/php-di/src/DI/Container.php(122): DI\Container->resolveDefinition(Object(DI\Definition\ObjectDefinition))
#9 /app/vendor/php-di/php-di/src/DI/Definition/AliasDefinition.php(63): DI\Container->get('Application\\Domain\\Rep...')
#10 /app/vendor/php-di/php-di/src/DI/Definition/Resolver/SelfResolver.php(34): DI\Definition\AliasDefinition->resolve(Object(DI\Container))
#11 /app/vendor/php-di/php-di/src/DI/Definition/Resolver/ResolverDispatcher.php(58): DI\Definition\Resolver\SelfResolver->resolve(Object(DI\Definition\AliasDefinition), Array)
#12 /app/vendor/php-di/php-di/src/DI/Definition/Resolver/ObjectCreator.php(209): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\AliasDefinition))
#13 /app/vendor/php-di/php-di/src/DI/Definition/Resolver/ObjectCreator.php(173): DI\Definition\Resolver\ObjectCreator->injectProperty(Object(ServiceProviderController), Object(DI\Definition\ObjectDefinition\PropertyInjection))
#14 /app/vendor/php-di/php-di/src/DI/Definition/Resolver/InstanceInjector.php(28): DI\Definition\Resolver\ObjectCreator->injectMethodsAndProperties(Object(ServiceProviderController), Object(DI\Definition\ObjectDefinition))
#15 /app/vendor/php-di/php-di/src/DI/Definition/Resolver/ResolverDispatcher.php(58): DI\Definition\Resolver\InstanceInjector->resolve(Object(DI\Definition\InstanceDefinition), Array)
#16 /app/vendor/php-di/php-di/src/DI/Container.php(219): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\InstanceDefinition))
#17 /app/application/modules/default/controllers/ControllerAbstract.php(90): DI\Container->injectOn(Object(ServiceProviderController))
#18 /app/vendor/zf1/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(281): ControllerAbstract->__construct(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http), Array)
#19 /app/vendor/zf1/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#20 /app/vendor/zf1/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#21 /app/vendor/zf1/zend-application/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#22 /app/public/index.php(226): Zend_Application->run()
#23 {main}
```

It has something to do with the generated proxies. The weird thing is:
- APCu is used to cache DefinitionFiles
- Proxy files are written to disk

This is on a Heroku deployment, so both APCu cache and the directory with proxy files are empty upon each deploy / restart of the application, so this should 'always' work... When I have the proxy files generated on the local development environment, that particular static property *is* available in the generated proxy file. So maybe a race condition / cache slam, which requires to warm the definition cache and generate all proxies before deploy to a production environment...

Will investigate further coming weeks

- PHP: 7.1.2
- APCu: 5.1.8
- php-di/php-di: 5.4.0
- ocramius/proxy-manager: 2.1.0

**Comment by mnapoli** [comment]
That's weird indeed :/ Can you access the files generated on Heroku and check what they look like (if they have the property)?

**Comment by holtkamp** [comment]
>Can you access the files generated on Heroku and check what they look like (if they have the property)

I could try this, but looking at the amount of involved proxy objects (437 files, 10MB) I decided it would be beter to make the generation of these proxy files part of the deploy procedure. Since I deploy the proxy files to Heroku, no such errors are written to the logs anymore, so I guess it was a cache slam while the proxies where generated, will monitor it, but this can be closed for now.
