### ISSUE TITLE
 Uncaught DI\NotFoundException: No entry or class found  ??

### ISSUE THREAD

**Issue by lvdesign** [PHP-DI/PHP-DI#688]
Hello, 
I work with php 7.1.23
and composer
"guzzlehttp/psr7": "^1.6",
        "http-interop/response-sender": "^1.0",       
        "zendframework/zend-expressive-fastroute": "^1.2",
        "twig/twig": "^2.12",
        "php-di/php-di": "^6.0"   
I work with the version 6.0.9 

I have this error message 👍 `Fatal error: Uncaught DI\NotFoundException: No entry or class found for 'Framework\Router\RouterTwigExtension' in /Applications/MAMP/htdocs/grapfikArt-php/monframework/vendor/php-di/php-di/src/Container.php:135 Stack trace: #0 /Applications/MAMP/htdocs/grapfikArt-php/monframework/vendor/php-di/php-di/src/Definition/Reference.php(53): DI\Container->get('Framework\\Route...') #1 /Applications/MAMP/htdocs/grapfikArt-php/monframework/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(59): DI\Definition\Reference->resolve(Object(DI\Container)) #2 /Applications/MAMP/htdocs/grapfikArt-php/monframework/vendor/php-di/php-di/src/Definition/Resolver/ArrayResolver.php(62): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\Reference)) #3 /Applications/MAMP/htdocs/grapfikArt-php/monframework/vendor/php-di/php-di/src/Definition/Resolver/ArrayResolver.php(47): DI\Definition\Resolver\ArrayResolver->resolveDefinition(Object(DI\Definition\Reference), Object(DI\Definition\ArrayDefinition), 0) #4 [intern in /Applications/MAMP/htdocs/grapfikArt-php/monframework/vendor/php-di/php-di/src/Definition/Resolver/ArrayResolver.php on line 66`

You could see my code here : https://github.com/lvdesign/monframework

I don't see in the doc a solution for this error.
Thanks for an advice
Cordially

**Comment by lvdesign** [comment]
Hello, find the problem in my code, a misspelling
