### ISSUE TITLE
Factories definitions using arrow functions ClosureAnalysisException

### ISSUE THREAD

**Issue by ManuelMolina97** [PHP-DI/PHP-DI#706]
Hello,

We have been using PHP-DI for around a month in development environment, and everything has been good so far. We tried to save in cache our definitions:

```php

$container->addDefinitions("{$rootDir}/config/{$_SERVER['PHP_ENV']}.php");
$container->useAutowiring(true);
$container->useAnnotations(false);

$container->addDefinitions([
    \Config\DatabaseConfig::class => fn(ContainerInterface $container) => new \Config\DatabaseConfig($container->get('databaseConfig')),
...
]);

    $container->enableCompilation(__DIR__ . '/cache');
    $container->writeProxiesToFile(true, __DIR__ . '/cache/proxies');
``` 

And when `writeProxiesToFile` was being executed, we got the following error:

```
2020/02/26 10:02:31 [error] 1100#1100: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught SuperClosure\Exception\ClosureAnalysisException: The closure was not found within the abstract syntax tree. in /var/www/wallet/vendor/jeremeamia/superclosure/src/Analyzer/AstAnalyzer.php:72
Stack trace:
#0 /var/www/pracmanduca/vendor/jeremeamia/superclosure/src/Analyzer/AstAnalyzer.php(30): SuperClosure\Analyzer\AstAnalyzer->locateClosure()
#1 /var/www/pracmanduca/vendor/jeremeamia/superclosure/src/Analyzer/ClosureAnalyzer.php(29): SuperClosure\Analyzer\AstAnalyzer->determineCode()
#2 /var/www/pracmanduca/vendor/php-di/php-di/src/Compiler/Compiler.php(373): SuperClosure\Analyzer\ClosureAnalyzer->analyze()
#3 /var/www/pracmanduca/vendor/php-di/php-di/src/Compiler/Compiler.php(322): DI\Compiler\Compiler->compileClosure()
#4 /var/www/pracmanduca/vendor/php-di/php-di/src/Compiler/Compiler.php(276): DI\Compiler\Compiler->compileValue()
#5 /var/www/pracmanduca/vendor/php-di/php-di/src/Compiler/Compiler.php(155): DI\Compiler\Compiler->compileDefinition()
#6 /var/www/pracmanduca/vendor/php-di/php-di/
```

We have tried the same example but without arrow functions, and it's working. So arrow functions are causing the issue, but why? We know context works different using arrow functions, but we're not using $this or anything similar in any of our factories.

PHP Version: 7.4.3
PHP-DI version: 6.0

**Comment by SvenRtbg** [comment]
I think arrow functions are not yet supported by SuperClosure. See https://github.com/jeremeamia/super_closure/issues/112 for the relevant issue.

**Comment by mnapoli** [comment]
Oh yeah good catch!

I was using short functions, but did not compile the container so I never saw the exception before.

**Comment by b1rdex** [comment]
Is https://github.com/opis/closure missing this too?

**Comment by b1rdex** [comment]
Ok, SuperClosure just became abandoned (https://github.com/jeremeamia/super_closure/commit/3d2c7f8cc47183c4d88520698fe6ec91e967ef28).

@mnapoli opis/closure supports short functions (https://github.com/opis/closure/commit/86fc51fce952567570e0629a22981665be02e7ff) so PHP-DI should migrate.

**Comment by nixoncode** [comment]
using Slim/Di-Bridge V3.0.1 in production. got the same error too 

>Package jeremeamia/superclosure is abandoned, you should avoid using it. Use opis/closure instead.

**Comment by b1rdex** [comment]
Guys, please take a look at #716. I replaced closure `jeremeamia/superclosure` w/ `opis/closure`, but there are some restrictions.
