### ISSUE TITLE
Some entries in compiled container aren't using FQCN in 6.2+

### ISSUE THREAD

**Issue by soren121** [PHP-DI/PHP-DI#724]
Apologies if this issue is in the wrong repo. 

I am using `php-di/slim-bridge` 2.0 for PHP-DI support in my Slim 3 application, as I have not been able to upgrade to Slim 4 yet. 

I ran `composer upgrade` today, bringing PHP-DI from 6.1.0 to 6.2.1, which broke my application with the following fatal error:

```
Error: Class 'AssociativeArrayResolver' not found in /var/app/api_prod/cache/php-di/CompiledContainer.php:610
Stack trace:
#0 [internal function]: CompiledContainer::{closure}(Object(CompiledContainer))
#1 /var/app/api_prod/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Object(Closure), Array)
#2 /var/app/api_prod/vendor/php-di/php-di/src/CompiledContainer.php(116): Invoker\Invoker->call(Object(Closure), Array)
#3 /var/app/api_prod/cache/php-di/CompiledContainer.php(617): DI\CompiledContainer->resolveFactory(Object(Closure), 'foundHandler.in...')
#4 /var/app/api_prod/vendor/php-di/php-di/src/CompiledContainer.php(53): CompiledContainer->get61()
#5 /var/app/api_prod/cache/php-di/CompiledContainer.php(596): DI\CompiledContainer->get('foundHandler.in...')
#6 /var/app/api_prod/cache/php-di/CompiledContainer.php(601): CompiledContainer->get60()
#7 /var/app/api_prod/vendor/php-di/php-di/src/CompiledContainer.php(53): CompiledContainer->get59()
```

This error seems to stem from the container configuration for `foundHandler.invoker` in slim-bridge. The following is the generated code for function `get61()` referenced in the stack trace:

```
protected function get61()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        $resolvers = [
            // Inject parameters by name first
            new AssociativeArrayResolver,
            // Then inject services by type-hints for those that weren't resolved
            new \Invoker\ParameterResolver\Container\TypeHintContainerResolver($c),
            // Then fall back on parameters default values for optional route parameters
            new \Invoker\ParameterResolver\DefaultValueResolver(),
        ];
        return new \Invoker\Invoker(new \Invoker\ParameterResolver\ResolverChain($resolvers), $c);
    }, 'foundHandler.invoker');
    }
```

And the following is the `get61()` function as generated by PHP-DI 6.1.0:

```
protected function get61()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
    $resolvers = [
        // Inject parameters by name first
        new \Invoker\ParameterResolver\AssociativeArrayResolver(),
        // Then inject services by type-hints for those that weren't resolved
        new \Invoker\ParameterResolver\Container\TypeHintContainerResolver($c),
        // Then fall back on parameters default values for optional route parameters
        new \Invoker\ParameterResolver\DefaultValueResolver(),
    ];
    return new \Invoker\Invoker(new \Invoker\ParameterResolver\ResolverChain($resolvers), $c);
}, 'foundHandler.invoker');
    }

```

As you can see, the array item for `AssociativeArrayResolver` is no longer generated with its fully-qualified class name in 6.2.0+, which throws a fatal error. I haven't found any reason why this should no longer work. Downgrading PHP-DI to 6.1.0 solved the issue.

**Comment by soren121** [comment]
Ah, never mind, I see that this is tracked in  php-di/slim-bridge#63, not sure how I missed that...
