### ISSUE TITLE
Namespace resolution missing for named parameter in CompiledContainer.php

### ISSUE THREAD

**Issue by flavioheleno** [PHP-DI/PHP-DI#855]
Hi! I've hit an interesting edge case that seems to be buggy.

When I add a definition using **named parameter** to pass a **namespaced class constant/enum**, the resulting compiled container fails to include the full namespace, yielding an error.

With a few pointers, I'm more than happy to provide a PR fixing the issue. Reproducible code below.

```php
// class.php
namespace My\Name\Space;
class MyClass {
  public const A = 1;

  public function __construct(string $arg1, int $arg2) {}
}
```

```php
// main.php
require_once __DIR__ . '/vendor/autoload.php';
include __DIR__ . '/class.php';

use My\Name\Space\MyClass;

$containerBuilder = new \DI\ContainerBuilder();
$containerBuilder
  ->enableCompilation(__DIR__)
  ->writeProxiesToFile(true, __DIR__);
$containerBuilder->addDefinitions(
  [
    MyClass::class => static function (): MyClass {
      return new MyClass(arg2: MyClass::A);
    }
  ]
);
$container = $containerBuilder->build();
$c = $container->get(MyClass::class);
```

```php
// CompiledContainer.php
<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'My\\Name\\Space\\MyClass' => 'get1',
);

    protected function get1()
    {
        return $this->resolveFactory(static function (): \My\Name\Space\MyClass {
      return new \My\Name\Space\MyClass(arg2: MyClass::A);
    }, 'My\\Name\\Space\\MyClass');
    }

}
```

```shell
$ php main.php
PHP Fatal error:  Uncaught Error: Class "MyClass" not found in /home/flavio/Documents/open-source/php-di-bug/CompiledContainer.php:13
Stack trace:
#0 [internal function]: CompiledContainer::{closure}()
#1 /home/flavio/Documents/open-source/php-di-bug/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()
#2 /home/flavio/Documents/open-source/php-di-bug/vendor/php-di/php-di/src/CompiledContainer.php(114): Invoker\Invoker->call()
#3 /home/flavio/Documents/open-source/php-di-bug/CompiledContainer.php(12): DI\CompiledContainer->resolveFactory()
#4 /home/flavio/Documents/open-source/php-di-bug/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get1()
#5 /home/flavio/Documents/open-source/php-di-bug/bug.php(20): DI\CompiledContainer->get()
#6 {main}
  thrown in /home/flavio/Documents/open-source/php-di-bug/CompiledContainer.php on line 13
```

**Comment by flavioheleno** [comment]
My initial investigation pointed the issue to https://github.com/laravel/serializable-closure rather than PHP-DI as it is used to "compile" the container code.
Will keep investigating and try to fix it in the right repository :-)

**Comment by flavioheleno** [comment]
new release tagged with the fix: https://github.com/laravel/serializable-closure/releases/tag/v1.3.1
I'll close this as the composer constraint will catch up with this.
