### ISSUE TITLE
Call to undefined function token_get_all()

### ISSUE THREAD

**Issue by zerowebcorp** [PHP-DI/PHP-DI#858]
I am getting the following error when enabling compilation `$containerBuilder->enableCompilation(__DIR__);`

```
NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function Laravel\SerializableClosure\Support\token_get_all() in /var/www/vendor/laravel/serializable-closure/src/Support/ReflectionClosure.php:829
Stack trace:
#0 /var/www/vendor/laravel/serializable-closure/src/Support/ReflectionClosure.php(843): Laravel\SerializableClosure\Support\ReflectionClosure->getFileTokens()
#1 /var/www/vendor/laravel/serializable-closure/src/Support/ReflectionClosure.php(747): Laravel\SerializableClosure\Support\ReflectionClosure->getTokens()
#2 /var/www/vendor/php-di/php-di/src/Compiler/Compiler.php(406): Laravel\SerializableClosure\Support\ReflectionClosure->getUseVariables()
#3 /var/www/vendor/php-di/php-di/src/Compiler/Compiler.php(353): DI\Compiler\Compiler->compileClosure()
#4 /var/www/vendor/php-di/php-di/src/Compiler/Compiler.php(307): DI\Compiler\Compiler->compileValue()
#5 /var/www/vendor/php-di/php-di/src/Compiler/Compiler.php(160): DI\Compiler\Compiler->compileDefinition()
#6 /var/www/vendor/php...
```

Here is my code. 

``` 
        $containerBuilder = new DI\ContainerBuilder;
        $containerBuilder->addDefinitions(__DIR__ . '/src/Definitions.php');
        $containerBuilder->enableCompilation(__DIR__);
        $container = $containerBuilder->build();
```

`PHP Version 7.4.33` running on alpine container 

PHP configure
```

'./configure' '--build=x86_64-alpine-linux-musl' '--host=x86_64-alpine-linux-musl' '--prefix=/usr' '--program-suffix=7' '--libdir=/usr/lib/php7' '--datadir=/usr/share/php7' '--sysconfdir=/etc/php7' '--localstatedir=/var' '--with-layout=GNU' '--with-pic' '--with-config-file-path=/etc/php7' '--with-config-file-scan-dir=/etc/php7/conf.d' '--disable-short-tags' '--enable-bcmath=shared' '--with-bz2=shared' '--enable-calendar=shared' '--enable-ctype=shared' '--with-curl=shared' '--enable-dba=shared' '--with-dbmaker=shared' '--with-gdbm' '--with-lmdb' '--enable-dom=shared' '--with-enchant=shared' '--enable-exif=shared' '--with-ffi=shared' '--enable-fileinfo=shared' '--enable-ftp=shared' '--enable-gd=shared' '--with-freetype' '--with-jpeg' '--with-webp' '--with-xpm' '--disable-gd-jis-conv' '--with-gettext=shared' '--with-gmp=shared' '--with-iconv=shared' '--with-imap=shared' '--with-imap-ssl' '--enable-intl=shared' '--enable-json=shared' '--with-ldap=shared' '--with-ldap-sasl' '--with-libedit' '--with-libxml' '--enable-mbstring=shared' '--with-mysqli=shared,mysqlnd' '--with-mysql-sock=/run/mysqld/mysqld.sock' '--enable-mysqlnd=shared' '--enable-opcache=shared' '--with-openssl=shared' '--with-kerberos' '--with-system-ciphers' '--with-password-argon2' '--enable-pcntl=shared' '--with-external-pcre' '--enable-pdo=shared' '--with-pdo-dblib=shared' '--with-pdo-mysql=shared,mysqlnd' '--with-pdo-odbc=shared,unixODBC,/usr' '--with-pdo-pgsql=shared' '--with-pdo-sqlite=shared' '--with-pgsql=shared' '--enable-phar=shared' '--enable-posix=shared' '--with-pspell=shared' '--without-readline' '--enable-session=shared' '--enable-shmop=shared' '--enable-simplexml=shared' '--with-snmp=shared' '--enable-soap=shared' '--with-sodium=shared' '--enable-sockets=shared' '--with-sqlite3=shared' '--enable-sysvmsg=shared' '--enable-sysvsem=shared' '--enable-sysvshm=shared' '--with-tidy=shared' '--enable-tokenizer=shared' '--with-unixODBC=shared,/usr' '--enable-xml=shared' '--enable-xmlreader=shared' '--with-xmlrpc=shared' '--enable-xmlwriter=shared' '--with-xsl=shared' '--with-zip=shared' '--with-zlib' '--disable-phpdbg' '--with-pear=/usr/share/php7' '--enable-fpm' '--enable-embed' '--enable-litespeed' 'build_alias=x86_64-alpine-linux-musl' 'host_alias=x86_64-alpine-linux-musl'

```

As you can see the enabled module includes `tokenizer` . PHP-Di works fine if I don't enable compilation

**Comment by zerowebcorp** [comment]
Turned out it wasn't enabled. I had to run `apk add php7-tokenizer` and restart php-fpm
